/* port/posix/winerror.h — POSIX shim: Win32 error/HRESULT codes used by the port. */
#ifndef PORT_POSIX_WINERROR_H
#define PORT_POSIX_WINERROR_H

#include "windef.h"

#define NO_ERROR 0
#define ERROR_SUCCESS 0
#define ERROR_INVALID_FUNCTION 1
#define ERROR_FILE_NOT_FOUND 2
#define ERROR_PATH_NOT_FOUND 3
#define ERROR_TOO_MANY_OPEN_FILES 4
#define ERROR_ACCESS_DENIED 5
#define ERROR_INVALID_HANDLE 6
#define ERROR_NOT_ENOUGH_MEMORY 8
#define ERROR_INVALID_ACCESS 12
#define ERROR_INVALID_DATA 13
#define ERROR_INVALID_PARAMETER 87
#define ERROR_CALL_NOT_IMPLEMENTED 120
#define ERROR_ARITHMETIC_OVERFLOW 534
#define ERROR_MORE_DATA 234
#define ERROR_INSUFFICIENT_BUFFER 122
#define ERROR_HANDLE_EOF 38
#define ERROR_HANDLE_DISK_FULL 39
#define ERROR_NOT_SUPPORTED 50
#define ERROR_INVALID_NAME 123
#define ERROR_ALREADY_EXISTS 183
#define ERROR_FILENAME_EXCED_RANGE 206
#define ERROR_BAD_COMMAND 22
#define ERROR_BAD_LENGTH 24
#define ERROR_NOT_READY 21
#define ERROR_GEN_FAILURE 31
#define ERROR_PROC_NOT_FOUND 127
#define ERROR_MOD_NOT_FOUND 126
#define ERROR_BROKEN_PIPE 109
#define ERROR_NO_UNICODE_TRANSLATION 1113
#define ERROR_CANNOT_IMPLEMENT 120

#define HRESULT_FROM_WIN32(x) ((HRESULT)(x) <= 0 ? (HRESULT)(x) : (HRESULT)(((x) & 0x0000FFFF) | (7 << 16) | 0x80000000))
#define HRESULT_FROM_NT(x) ((HRESULT)((x) | 0x10000000))
#define HRESULT_FROM_SETUPAPI(x) HRESULT_FROM_WIN32(x)

#endif /* PORT_POSIX_WINERROR_H */
